apiVersion: v1
kind: Service
metadata:
  name: phonebookapi
  labels:
    app: phonebook
    component: api
spec:
  ports:
   - port: 8080
     targetPort: 8080
  selector:
   app: phonebook
   component: api