apiVersion: apps/v1
kind: Deployment
metadata:
  name: phonebookapi
spec:
  selector:
    matchLabels:
      app: phonebook
      component: api
  replicas: 1
  template:
    metadata:
      labels:
        app: phonebook
        component: api
    spec:
      containers:
        - name: phonebookapi
          image: image-registry.openshift-image-registry.svc:5000/myphonebook/myphonebook_api:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: phonebookapi-config
            - secretRef:
                name: phonebookapi-secret
