apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: phonebook
      component: db
  replicas: 1
  template:
    metadata:
      labels:
        app: phonebook
        component: db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"       
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: phonebookdb-secret