apiVersion: batch/v1
kind: Job
metadata:
  name: dbinit
spec:
  template:
    spec:
      containers:
      - name: dbinit
        image: docker-registry.default.svc:5000/phonebook/db_init
        envFrom:
            - configMapRef:
                name: phonebookapi-config
            - secretRef:
                name: phonebookapi-secret
      restartPolicy: Never
  backoffLimit: 4
