apiVersion: batch/v1
kind: Job
metadata:
  name: dbinit
spec:
  template:
    spec:
      containers:
      - name: dbinit
        image: image-registry.openshift-image-registry.svc:5000/myphonebook/db_init
        envFrom:
            - configMapRef:
                name: phonebookapi-config
            - secretRef:
                name: phonebookapi-secret
      restartPolicy: Never
  backoffLimit: 4
