apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: phonebook
    component: db
spec:
  type: ClusterIP
  ports:
   - port: 5432
  selector:
    app: phonebook
    component: db